# Generated by Django 3.1.1 on 2020-10-13 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_product', '0004_productgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgallery',
            name='Product',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='eshop_product.product'),
        ),
    ]
