# Generated by Django 3.1.1 on 2020-11-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_product', '0006_product_visit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bestselling',
            field=models.IntegerField(default=0),
        ),
    ]
