# Generated by Django 3.1.1 on 2020-10-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_product', '0001_initial'),
        ('eshop_tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='products',
            field=models.ManyToManyField(blank=True, to='eshop_product.Product'),
        ),
    ]
