# Generated by Django 3.1.1 on 2020-10-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_sliders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='description',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='link',
            field=models.URLField(default=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='title',
            field=models.CharField(default=True, max_length=150),
        ),
    ]
